Change untar permissions from 750 to 740
Because I'm getting this error when trying to run Lynis:

```text
Fatal error: permissions of file /opt/lynis/db/languages/en are not strict enough. Access to 'group' should be read-write, read, or none. Change with: chmod g=r /opt/lynis/db/languages/en
```